name: AWS Login
description: Login to AWS with duplo creds
runs:
  using: composite
  steps:
  - uses: actions/setup-python@v4

  - uses: BSFishy/pip-action@v1
    with:
      packages: |
        duplocloud-client

  - id: install-aws-cli
    uses: unfor19/install-aws-cli-action@v1

  - name: Install Duploctl
    shell: bash
    run: |
      export STS AWS_ACCESS_KEY_ID AWS_SECRET_ACCESS_KEY AWS_SESSION_TOKEN AWS_DEFAULT_REGION AWS_REGION AWS_ACCOUNT_ID

      STS="$(duploctl jit aws)"
      AWS_ACCESS_KEY_ID="$(echo "$STS" | jq -r '.AccessKeyId')"
      AWS_SECRET_ACCESS_KEY="$(echo "$STS" | jq -r '.SecretAccessKey')"
      AWS_SESSION_TOKEN="$(echo "$STS" | jq -r '.SessionToken')"
      AWS_DEFAULT_REGION="$(echo "$STS" | jq -r '.Region')"
      AWS_REGION="$AWS_DEFAULT_REGION"
      AWS_ACCOUNT_ID="$(aws sts get-caller-identity --query "Account" --output text)"

      cat <<EOF >> $GITHUB_ENV
      export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
      export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
      export AWS_SESSION_TOKEN=$AWS_SESSION_TOKEN
      export AWS_DEFAULT_REGION=$AWS_DEFAULT_REGION
      export AWS_REGION=$AWS_REGION
      export AWS_ACCOUNT_ID=$AWS_ACCOUNT_ID
      EOF
