openapi: "3.1.0"
info:
  title: Example Pet Store
  description: A Pet Store API.
  version: '1.0'
paths:
  "/pets":
    get:
      operationId: GET HTTP
      parameters:
      - name: type
        in: query
        schema:
          type: string
      - name: page
        in: query
        schema:
          type: string
      responses:
        '200':
          description: 200 response
          headers:
            Access-Control-Allow-Origin:
              schema:
                type: string
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/Pets"
      x-amazon-apigateway-integration:
        type: HTTP_PROXY
        httpMethod: GET
        uri: "arn:aws:apigateway:123456789:lambda:path/2015-03-31/functions/arn:aws:lambda:us-west-2:123456789:function:duploservices-dev01-rr-player-revoke-session/invocations"
        payloadFormatVersion: 1

x-amazon-apigateway-cors:
  allowOrigins:
  - "*"
  allowMethods:
  - GET
  - OPTIONS
  - POST
  allowHeaders:
  - x-amzm-header
  - x-apigateway-header
  - x-api-key
  - authorization
  - x-amz-date
  - content-type
components:
  schemas:
    Pets:
      type: array
      items:
        "$ref": "#/components/schemas/Pet"
    Empty:
      type: object
    NewPetResponse:
      type: object
      properties:
        pet:
          "$ref": "#/components/schemas/Pet"
        message:
          type: string
    Pet:
      type: object
      properties:
        id:
          type: string
        type:
          type: string
        price:
          type: number
    NewPet:
      type: object
      properties:
        type:
          "$ref": "#/components/schemas/PetType"
        price:
          type: number
    PetType:
      type: string
      enum:
      - dog
      - cat
      - fish
      - bird
      - gecko
