name: Validate Module
description: Test a single Terraform module
inputs:
  wkdir: 
    description: Working directory
    required: true
  gha_token:
    description: GitHub token
    required: true
runs:
  using: composite
  steps:

  - name: TF Init Module
    shell: bash
    working-directory: ${{ inputs.wkdir }}
    run: terraform init

  - name: Init TFLint
    shell: bash
    run: tflint --init -c ../../.tflint.hcl
    working-directory: ${{ inputs.wkdir }}

  - name: TF Validate Module
    shell: bash
    working-directory: ${{ inputs.wkdir }}
    run: terraform validate

  - name: Run TFLint
    shell: bash
    working-directory: ${{ inputs.wkdir }}
    run: tflint -c ../../.tflint.hcl
    env:
      GITHUB_TOKEN: ${{ input.gha_token }}

  - name: Validate Format
    shell: bash
    working-directory: ${{ inputs.wkdir }}
    run: terraform fmt -check=true -diff=true -recursive

