name: Install TF Dependencies
description: Install Terraform dependencies
inputs:
  tf_cache_dir:
    description: Terraform cache directory
    required: false 
    default: ~/.terraform.d/plugin-cache
runs:
  using: composite
  steps:
  
  - name: Setup Python
    uses: actions/setup-python@v4

  - name: Install duploctl
    uses: BSFishy/pip-action@v1
    with:
      packages: |
        duplocloud-client

  - name: Install AWS CLI
    id: install-aws-cli
    uses: unfor19/install-aws-cli-action@v1

  
