name: Test Modules

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  tfmodule:
    name: Testing ${{ matrix.module }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        module:
        - eks-nodes
        - micro-service
        - standalone-alb
        - tenant-role-extension
    env:
      DUPLO_TOKEN: ${{ secrets.DUPLO_TOKEN }}
      DUPLO_HOST: ${{ vars.DUPLO_HOST }}
      DUPLO_TENANT: ${{ vars.DUPLO_TENANT }}
      TF_LOCKFILE: ./modules/${{ matrix.module }}/.terraform.lock.hcl
    steps:

    - uses: actions/checkout@v3
      name: Checkout source code

    

